name: app_eventos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  loading_animation_widget: ^1.2.1 
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  table_calendar: ^3.1.2
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/logo.png
  - assets/google_icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700





